version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    network_mode: "host"

  tgbot:
    container_name: bot
    build:
      context: .
    network_mode: "host"

    command: python app.py
    restart: always

    env_file:
      - ".env"